apiVersion: v1
kind: ConfigMap
metadata:
  name: msvc-cursos
data:
  port: "8001"
  db_host: mysql8:3306
  database: msvc_usuarios
  username: root
  password: sasa
  curso_url: msvc_cursos:8002
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: msvc-cursos
data:
  port: "8002"
  db_host: postgres:5432
  database: msvc_cursos
  username: postgres
  password: sasa
  curso_url: msvc_cursos:8001