apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  storageClassName: standar
  accessModes:
    - ReadWriteOnce
persistentVolumeClaim:
  claimName: postgres-pvc